[build]
  functions = "functions"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[dev]
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200